### ISSUE TITLE
Reference instance to test goblin against

### ISSUE THREAD

**Issue by fridex** [davebshow/goblin#100]
Hi @davebshow,

I am trying to make goblin work. I have tried different versions of gremlin so far (mostly backed by elasticsearch as we want to use ES), but without success (however, I was able to make work raw gremlinpython). I dived into sources a bit and found this restriction https://github.com/davebshow/goblin/blob/master/goblin/app.py#L54 which says that goblin app works only with graphson of version 1. Is this still relevant? I haven't found any python implementation for graphson in version 1 (only version 2 and 3).

Also, is there some "reference" instance (a docker image or docker-compose) that I could use to make goblin work? What is preferred gremlin version to be used (I saw https://github.com/davebshow/goblin/issues/85#issuecomment-336999649)?

BTW goblin sometimes gets stuck and (if configured) terminates with timeout error when there were issues on remote (e.g. serialization issues). Is there a way how to bypass such behavior?

Thanks!

**Comment by fridex** [comment]
Tried with the latest JanusGraph release (0.2.0 as of now) with aiogremlin==3.2.6rc1 gremlinpython==3.2.6 goblin==2.1.0, it looks like it works for me.

**Comment by davebshow** [comment]
That is good. Typically I ensure that aiogremlin/goblin run against the current TinkerGraph implementation. I have a fair few Janus users that typically keep me honest there as well. 

Goblin as it currently exists in GitHub master should run with  aiogremlin/gremlinpython 3.2.6 + (3.2.6, 3.2.7, 3.3.0, 3.3.1), using GraphSON2 or 3. I hope to formalize a release of Goblin soon that works well with Neptune, but I have been too busy (this is all a side project for me now, changed jobs). 

So, you should be able to install the current Goblin and the aioremling/gremlinpython combo that matches the TinkerPop number for your provider (3.2.6 for Janus 0.2.0), and it should work out of the box.

Not really sure what you mean about the timeouts. Could you be a be more specific (example maybe)?

**Comment by fridex** [comment]
> Not really sure what you mean about the timeouts. Could you be a be more specific (example maybe)?

I was not able to reproduce it with the currently installed stack. If encounter some issues, I will report back.

Thanks!
