### ISSUE TITLE
Deserializing arbitrary (non-element) results

### ISSUE THREAD

**Issue by leifurhauks** [davebshow/goblin#12]
Some queries return results that aren't vertices or edges, for example:

```
result = await session.traversal(MyVertex).has(MyVertex.some_prop, 'some_value').count()
```

Which returns an integer.

A more complex example:

```
result = await (session.traversal(MyVertex)
                .has(MyVertex.some_prop, 'some_value').as('v1')
                .out('some_label').as('v2')
                .select('v1', 'v2').by().by('a_string_property'))
```

This will return a mapping of vertices ('v1') to strings (from a property of 'v2'), something like:

```
{
    v[xyz]: 'some_string',
    ...
}
```

**Comment by davebshow** [comment]
Well commit 864bcca398cf478d99d446d6fbe56c8cefc122b1 allows you to get results from any traversal. How to handle complex deserialization should be discussed with support in a future release.

**Comment by davebshow** [comment]
I am going to close this issue since you already fixed this @leifurhauks
