### ISSUE TITLE
module 'goblin' has no attribute 'driver'

### ISSUE THREAD

**Issue by 37** [davebshow/goblin#24]
Running 'pip3 install goblin' had me seemingly install goblin successfully, though I'm having a bit of trouble running the examples found in the documentation. 

I cannot do:

```
from goblin import driver
```

and when I attempt to access goblin.driver (just importing goblin) I recieve:

```
module 'goblin' has no attribute 'driver'
```

Any help would be greatly appreciated.

**Comment by davebshow** [comment]
I suspect that you are using an older version of Goblin. Please check the version of Goblin that you have installed using something like `pip show goblin`, if it is not 1.0.0a3, please use `pip install goblin==1.0.0a3`. This should fix the problem. Note that there will be a new release of Goblin with API breaking changes this weekend.

Thanks for your interest!

**Comment by davebshow** [comment]
I will assume this issue is closed. Feel free to reopen if you are still having problems.
