### ISSUE TITLE
goblin doesn't work with Titan 1.0.0 out of the box

### ISSUE THREAD

**Issue by mikedewar** [davebshow/goblin#28]
When running the quickstart Titan (titan-1.0.0-hadoop1/bin/titan.sh start) and then trying to follow along with the goblin docs, it turns out that goblin is trying to speak `application/vnd.gremlin-v2.0+json` which the default gremlin-server install packaged with Titan doesn't understand. 

If I edit the gremlin-server.yaml and add to the serializers 

```
- { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV2d0, config: { useMapperFromGraph: graph }}
```

which from some googling I have some expectation to bless the gremlin server with the ability to speak the correct dialect I get, from the gremlin-server logs:

```
13217 [main] WARN  org.apache.tinkerpop.gremlin.server.AbstractChannelizer  - Could not find configured serializer class - org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV2d0 - it will not be available
```

While I appreciate this might not really be goblin's problem, and that I need somehow to update my gremlin-server, goblin is my route into learning gremlin/titan etc, so it might be nice for goblin somewhere to specify it needs a certain version of gremlin when connecting to the server.

Incidentally, if I run the `1+1` example in your docs with the default gremlin-server that comes with Titan it just hangs forever - it isn't noticing that the server has spat out its pacifier.

**Comment by davebshow** [comment]
Hi Mike,
GraphSON2 is implemented in TinkerPop 3.2.2+, unless you are using GremlinServer 3.2.2 +, adding `GraphSONMessageSerializerGremlinV2d0` to the conf won't do anything. However, as stated in the [docs](http://goblin.readthedocs.io/en/latest/#a-note-about-graphson-message-serialization), Goblin comes packaged with a GraphSON1 message serializer to allow for backwards compatibility. To use it, import it and pass it to the config of whatever object you need to use it with:

``` python
from goblin.driver.serializer import GraphSONMessageSerializer
conn = await driver.Connection.open(
    'ws://localhost:8182/gremlin', loop,  message_serializer=serializer.GraphSONMessageSerializerr)
```

A side note: I would recommend using Titan 1.1. It still doesn't use GraphSON2, but it seems to perform much better than Titan 1.0. You can build it from source. Something like (untested):

```
git clone https://github.com/thinkaurelius/titan -b titan11 titan11
cd titan11
mvn clean install -DskipTests=true -Dgpg.skip=true -Paurelius-release
unzip titan-dist/titan-dist-hadoop-2/target/titan-1.1.0-SNAPSHOT-hadoop2.zip
```

**Comment by mikedewar** [comment]
Thanks for this! Apologies for missing the huge, well structured note on this that you quite deliberately put on the very first and main page of the documentation where fools like me couldn't possibly miss it. For whatever reason I hadn't considered that goblin would be back-portable.  

Will check out Titan 1.1.

**Comment by davebshow** [comment]
Lol no worries! Thanks for your interest and feel free to reach out if there is anything else.

**Comment by mansoure** [comment]
Hi Dave,
Thank you very much for your help.
I have built Titan 1.1 following your instructions at [1].
When I start the gremlin-server 
bin/gremlin-server.sh
I get  warnings such as  GraphFactory message: GraphFactory could not instantiate this Graph implementation [class com.thinkaurelius.titan.core.TitanFactory].
But the server starts. 

What is not clear to me how to use the GraphSONMessageSerializer?
I tried your code:
conn =  driver.Connection.open(
    'ws://localhost:8182/gremlin', loop,  message_serializer=serializer.GraphSONMessageSerializerr)

But I get this error
AttributeError: module 'goblin.driver.serializer' has no attribute 'GraphSONMessageSerializerr'

I am using this python version 
Python 3.5.2 :: Anaconda 4.2.0 (x86_64)

**Comment by mansoure** [comment]
I also tried to use GraphSONMessageSerializer in the following code
////////////////////////
loop = asyncio.get_event_loop()
remote_conn = loop.run_until_complete(goblin.driver.Connection.open(
    "http://localhost:8182/gremlin",
    loop, message_serializer=GraphSONMessageSerializer))

app = loop.run_until_complete(goblin.Goblin.open(loop))
////////////////////////

I get this error the below error. It might be a configuration problem for the websocket.  Any idea?

////////////////////////
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<Connection._receive() running at /Users/emansour/anaconda/lib/python3.5/site-packages/goblin/driver/connection.py:257> wait_for=<Future pending cb=[Task._wakeup()]>>
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10b8afa20>
ERROR:asyncio:Unclosed response
client_response: <ClientResponse(ws://localhost:8182/gremlin) [101 Switching Protocols]>
<CIMultiDictProxy('Upgrade': 'websocket', 'Connection': 'Upgrade', 'Sec-Websocket-Accept': 'RcRB3v5vWmJhhMLWx4k3REXNLS0=')>

**Comment by mansoure** [comment]
>>>I get warnings such as GraphFactory message: GraphFactory could not instantiate this Graph >>>implementation [class com.thinkaurelius.titan.core.TitanFactory].
>>>But the server starts.

In the gremlin-server.yaml, I used titan-berkeleyje-server.properties instead of titan-cassandra-es-server.properties as the following the following 
graphs: {
    graph: conf/gremlin-server/titan-berkeleyje-server.properties}

Now, when I run the server 
bin/gremlin-server.sh conf/gremlin-server/gremlin-server.yaml

I do not get that warning.

**Comment by davebshow** [comment]
> But I get this error
> AttributeError: module 'goblin.driver.serializer' has no attribute 'GraphSONMessageSerializerr'

I assume you figured out what was going on here.

> I get this error the below error. It might be a configuration problem for the websocket. Any idea?

This is happening because you are opening connections and not closing them. Most goblin objects have a close [coroutine](http://goblin.readthedocs.io/en/latest/goblin.driver.html#goblin.driver.connection.Connection.close) that should be called when you are finished.

> In the gremlin-server.yaml, I used titan-berkeleyje-server.properties instead of titan-cassandra-es-server.properties as the following the following.

I'm not really sure what is going on with Titan or its config. Don't have tons of experience there.

**Comment by mansoure** [comment]
Thank you very much for your help. 
What do you think about Janusgraph https://github.com/JanusGraph/janusgraph ?

**Comment by davebshow** [comment]
Well, Titan is now Janus. As long as the community gets involved I think there is a lot of potential there. Hopefully the backing from LSF will help get things rolling. Other than that, DSE Graph is a nice option, although it isn't free for commercial use.
