### ISSUE TITLE
204 responses

### ISSUE THREAD

**Issue by leifurhauks** [davebshow/goblin#3]
We may want the driver to handle 204 messages specially, e.g. by returning an empty response to the caller.

Also we were talking about breaking apart the response messages into their components for easier consumption; in this case we would definitely need to handle 204 specially because callers won't be interacting with messages directly.

**Comment by davebshow** [comment]
What would you propose to change for 204 responses?

For the second part, are you referring to breaking up the chunked message that are returned by the server? If so, this is already being done in goblin as messages are deserialized to ogm objects. I think though I prefer to handle this at the ogm level, while having the driver return chunks sized as specified by the server conf. It may seem a little low level, but it gives the driver user more control. I am open to discussing this though...

**Comment by leifurhauks** [comment]
Re: breaking up the chunks, I guess I was thinking of the chunking as being a transport matter, and not something that needed to be dealt with by code that uses the driver.

I think [gremlin-driver](http://tinkerpop.apache.org/javadocs/current/full/index.html?org/apache/tinkerpop/gremlin/driver/package-summary.html) doesn't expose messages directly to the driver user, instead returning a `ResultSet`, a stream of `Result`s.

**Comment by davebshow** [comment]
Yeah, that makes sense I suppose. Do we want to get rid of the concept of the `Message` entirely then and only return results? Or, should each result be a `Message` that includes meta data...?

**Comment by leifurhauks** [comment]
I guess it depends on whether we have a need for `Message` internally.

**Comment by davebshow** [comment]
Commit 66049a0a49cbf1fa1892bb96d66f8e5e296516e2 resolves this.
