### ISSUE TITLE
Does it really not work with versions of titan before titan11 which is not an official release ?

### ISSUE THREAD

**Issue by decebal** [davebshow/goblin#46]
I wanted to use goblin with titan 1.0.0 which is the latest mature version of titan, but I had issues even at the most simple operations like adding a vertex :( 
It looks like the mature version of titan does not come with GraphSON2 , but GraphSON1 which is some pain provider on my part .

**Comment by davebshow** [comment]
You should be able to use Goblin with Titan 1.0. To do so, you must make sure that you are using the correct [message serializer](http://goblin.readthedocs.io/en/latest/#a-note-about-graphson-message-serialization). Regardless, I would highly recommend that you build  Titan1.1 from source. I don't think it is being actively developed, as all activity has been moved to [JanusGraph](https://github.com/JanusGraph/janusgraph). Note: you will still have to use GraphSON1 regardless of what version of Titan you use.

If you can't get it to work, please provide more information i.e., the code that is failing, error logs, etc. and I will help you sort out your issue.
