### ISSUE TITLE
Creating an edge results in a TypeError

### ISSUE THREAD

**Issue by Will-Hardman** [davebshow/goblin#55]
Hi Dave,

I've been working with your library for most of today but have stumbled upon a bit of an issue.  I wonder if you have seen this before?

I'm using Titan 1.1 (built from source), with TinkerPop 3.2.3 and an embedded Cassandra database.

Adding an edge throws a `TypeError: unhashable type: 'dict'` in line 350 of `save_edge()`.

The following minimal code replicates my error:

```
loop = asyncio.get_event_loop()

app = loop.run_until_complete(goblin.Goblin.open(loop,
                                                 hosts = ['localhost'],
                                                 port = '8182',
                                                 scheme = 'ws'))

async def create(app, data):
    session = await app.session()
    session.add(data)
    await session.flush()
    return data

class myVertex(goblin.Vertex):
    pass

class myEdge(goblin.Edge):
    pass

v1 = myVertex()
v1 = loop.run_until_complete(create(app, v1))

v2 = myVertex()
v2 = loop.run_until_complete(create(app, v1))

e = myEdge()
e.source = v1
e.target = v2
loop.run_until_complete(create(app, e))
```

What could be the source of this?

With regards,

Will

**Comment by Will-Hardman** [comment]
It's worth noting that the edge *does* get created.  I can then traverse it without problems.  But if I attempt to retrieve an edge I get the same error, this time thrown by another method.

**Comment by davebshow** [comment]
I believe this is a (de)serialization error caused by the server version. Goblin now relies on the `aiogremlin` language variant version 3.2.4, which requires TinkerPop (Gremlin Server) 3.2.4. I would recommend bumping to the current Gremlin Server version for your app. The other option would be to use the previous version of Goblin. Let me know if this works for you.

**Comment by Will-Hardman** [comment]
Hi Dave,

Thanks for getting back to me so speedily!

I tried building Titan 1.1 with TinkerPop 3.2.4 but was getting an error like:

 `Can't construct a java object for tag:yaml.org,2002:org.apache.tinkerpop.gremlin.server.Settings; exception=Cannot create property=ssl for JavaBean=org.apache.tinkerpop.gremlin.server.Settings@33f88ab; java.lang.reflect.InvocationTargetException`

So I guess I'll need to try an older version of Goblin.  Which one would you recommend?

Will

**Comment by davebshow** [comment]
If I'm not mistaken, 1.0.0b2 should work just fine with TP 3.2.3. You should be able to install with pip:

```
$ pip install goblin==1.0.0b2
```

As a side note, have you considered moving from Titan to [JanusGraph](http://janusgraph.org/)? Titan is no longer active and won't see any new releases. I'm sure upcoming releases of JanusGraph will support TP 3.2.4+, which includes a lot of improvements. I believe the most recent release only tests against 3.2.3, but you may be able to build it with 3.2.4...

**Comment by Will-Hardman** [comment]
Hi Dave,

Thanks for your thoughts above.  I'm on vacation this week but will update you as soon as I'm back.

Regarding JanusGraph - I briefly considered it but then decided that it was too early in development to risk using.  However, a closer inspection of the docs suggests that it might be a fork of the Titan codebase?  In any case, it's a good shout and I'll probably migrate.

With regards,

Will

**Comment by davebshow** [comment]
Yes JanusGraph is Titan under a new name. If you don't mind me asking, what are you using Goblin/TinkerPop for? If it's top secret no worries, if it is semi-secret feel free to email me at davebshow@gmail.com.

**Comment by Will-Hardman** [comment]
Hi Dave,

So I've had a chance to resolve the issues (switching to the JanusGraph 0.11 release in the process).

- I pulled Goblin 1.0.0b2 from pip but it started throwing different errors: for example it seems that traversals like `g().V().iterate()` were not supported by the corresponding version of aiogremlin.

- I tried building from the Master branch of JanusGraph - which does depend on TP 3.2.4 - but I get errors at runtime when forking Elasticsearch ("cannot run as root").

So I guess the best solution is to wait for JanusGraph 0.2, unless I've missed something else?

I'll email you separately about my use case :-)

With regards,

Will

**Comment by davebshow** [comment]
Yes, the 1.0.0b2 version features a "special" version of the GLV. Since the 2.0.0 release (which uses `aiogremlin`), we support the official gremlin-python GLV API.

Regarding building the Master branch of JanusGraph, I'm not sure what is going on there. I know that they provide great support through their [Google group](https://groups.google.com/forum/#!forum/janusgraph-users).

**Comment by davebshow** [comment]
Has this been resolved?

**Comment by John-Boik** [comment]
Hi Dave. I'm getting a similar error as Will did. So I built JanusGraph from scratch, using TP 3.2.5.  Using Will's code (as well as the sample code in the Goblin docs), I get the same error that I received when I was using JanusGraph 0.1.1. It seems that a dict is trying to use a dict as a key. Any ideas on how I might fix this? Or, perhaps I am doing something wrong. 

Traceback (most recent call last):
  File "run_janus.py", line 37, in <module>
    loop.run_until_complete(create(app, e))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "run_janus.py", line 19, in create
    await session.flush()
  File "/home/john/.virtualenvs/ETR/lib/python3.5/site-packages/goblin/session.py", line 270, in flush
    await self.save(elem)
  File "/home/john/.virtualenvs/ETR/lib/python3.5/site-packages/goblin/session.py", line 312, in save
    result = await self.save_edge(elem)
  File "/home/john/.virtualenvs/ETR/lib/python3.5/site-packages/goblin/session.py", line 350, in save_edge
    self.current[hashable_id] = result
  File "/home/john/.virtualenvs/ETR/lib/python3.5/weakref.py", line 158, in __setitem__
    self.data[key] = KeyedRef(value, self._remove, key)
TypeError: unhashable type: 'dict'
Task was destroyed but it is pending!

**Comment by davebshow** [comment]
Well here I think this is because JanusGraph uses hashes for IDs...some other users have used this function to work with JanusGraph. You can then pass as the `get_hashable_id` kwarg to the `Goblin.open` method:

```python
def get_hashable_id(val):
    #Use the value "as-is" by default.
    result = val
    if isinstance(val, dict) and "@type" in val and "@value" in val:
        if val["@type"] == "janusgraph:RelationIdentifier":
            result = val["@value"]["value"]
    return result
```
See example code here and see if that fixes your issue: https://github.com/davebshow/goblin/issues/60

**Comment by John-Boik** [comment]
Good to go, Dave. Thanks for the quick response.

**Comment by StanYaha** [comment]
Hello, if i insert millions of points, What about efficiency？

**Comment by StanYaha** [comment]
If i insert millions of Vertex, Edge, What about the efficiency?
Sorry about my English

**Comment by dyangelo-grullon** [comment]
I received this error as well, and although the workaround provided is an adequate solution, I feel as if goblin should be vendor agnostic. Can't the 'get_hashable_id' callback that you've provided be the default callback?

**Comment by davebshow** [comment]
The whole point of allowing users to pass a hasher as a kwarg is so that goblin is vendor agnostic. For example, DSE Graph requires a different hashing function. The default implementation of `Goblin` should run against the reference implementation TinkerGraph, which does not require a hasher.

**Comment by dyangelo-grullon** [comment]
Thank you for clarifying!
