### ISSUE TITLE
Issues with aliases when submitting Gremlin through Cluster object

### ISSUE THREAD

**Issue by oberonv1** [davebshow/goblin#56]
Hey Dave,

I've been attempting to communicate with DSE graph 5.10 through Goblin with the following code:
```
async def gremlin_query(script, port, alias=None):
    eventloop = asyncio.get_event_loop()
    if alias is None:
        cluster = await Cluster.open(eventloop, port=port)
    else:
        cluster = await Cluster.open(eventloop, aliases=alias, port=port)
    client = await cluster.connect()
    resp = await client.submit(script)
    messages = []
    async for msg in resp:
        messages.append(msg)
    await cluster.close()
    return messages
```

The alias is defined as `{ 'g': 'test_graph.g' }`
When run against the DSE Gremlin Server, I get the following error:
```
aiogremlin.exception.GremlinServerError: 500: 500: Unknown value type for: class java.util.LinkedHashMap
```

This works fine when used in the context of a `Session` object  like so:
```
async def create_session(self):
        eventloop = asyncio.get_event_loop()
        self.app = await Goblin.open(eventloop,
                                     get_hashable_id=self.adapter.get_hashable_id,
                                     aliases=self.adapter.get_alias('test_graph'),
                                     port=self.adapter.port)
        self.app.register(User, LivesIn)
        session = await self.app.session()
        return session
```
Where `self.adapter.get_alias('test_graph')` returns `{ 'g': 'test_graph.g' }`.
Perhaps the `Cluster` class from aiogremlin is having trouble serializing the dictionary? Don't really have a clue...

Any help would be appreciated!

**Comment by davebshow** [comment]
Initially I am a bit confused by this, as the `App`/`Session` approach in Goblin uses nearly the exact same mechanics to set the aliases on the underlying `Cluster`/`Client` classes (now from the `aiogremlin` module). Furthermore, it appears that aliases are be properly set by the `aiogremlin` code, I can add these [two tests](https://github.com/davebshow/aiogremlin/commit/33567e966fbc4dc8c2a1f98e1eda829ccedce54f)--based on your failing code--that run against TP 3.2.4.

I don't currently have an instance of DSE up and running, but I'd be happy to get one going and see if I can help figure out what is going on. First, I need some more info: 

* Versions for: `goblin`, `DSE`, and `TinkerPop` (Gremlin Server)
* Any relevant config for `DSE` that is different from the default
* An example script you are sending to the server when you get the error
* A small snippet of your code that calls the `gremlin_query` function

**Comment by davebshow** [comment]
Thinking more, let's just start with versions before you do the work of pasting a bunch of code here.

**Comment by oberonv1** [comment]
Apologies for the delay, was away for the weekend.

My mistake, I just attempted to submit a gremlin query with the following `Session` code:
```
eventloop = asyncio.get_event_loop()
adapter = DseAdapter()
app = await Goblin.open(eventloop,
                            get_hashable_id=adapter.get_hashable_id,
                            aliases=adapter.get_alias('test_graph'),
                            port=port)
session = await app.session()
remote_traversal = await session.submit(script)
results = await remote_traversal.side_effects.keys()
return results
```

It results in the same `Unknown value type for: class java.util.LinkedHashMap` error, so it seems it is indeed not functioning with the underlying `Cluster/Client` classes.

Versions:
- DSE: 5.1.0
- Goblin: 2.0.0
- Tinkerpop: This was a bit tricky, but when I enter `Gremlin.version()` into the gremlin console connected to the DSE Server, it gave me `3.2.5-20170222-de2f4034`

Made no edits to the DSE config files. This is stock DSE 5.1.0
Script I am currently trying to get working: `schema.config().option('graph.schema_mode').set('Development')`

I need to set the `schema` object to [Development mode](https://stackoverflow.com/questions/38464443/dse-gremlin-console-cannot-modify-schema) in order to add anything without a pre-defined schema.

Example call to `gremlin_query`:
```
async def create_graph(self, graph_name):
        print('CREATING GRAPH \n')
        # In order to insert data, schema must first be set to Development mode
        # default is Production, where schema must be defined before data
        dev_mode = "schema.config().option('graph.schema_mode').set('Development')"
        await gremlin_query(dev_mode, self._port, self.get_alias(graph_name))
```

I appreciate the help!

**Comment by davebshow** [comment]
Thanks for the info. I'll get DSE up and running as soon as I can and see if I can figure out what is going on. If not today, you will hear back from me tomorrow at the latest.

**Comment by davebshow** [comment]
Turns out I had some time this morning. I downloaded the latest version of DSE (5.1.1), and I can't seem to reproduce this error. Maybe try upgrading to 5.1.1. I simply used `aiogremlin` here to send messages to the server:

* Started the server:

```
$ ./bin/dse cassandra -g
```

* Created a graph with the Gremlin Console:

```
$ ./bin/dse gremlin-console

gremlin> system.graph('test').create()
==>null
gremlin> system.graphs()
==>test
```

* Wrote a script using `aiogremlin`:

```python
import asyncio
from aiogremlin import driver

loop = asyncio.get_event_loop()

async def test_dse(loop):
    cluster = await driver.Cluster.open(loop, aliases={'g': 'test.g'})
    client = await cluster.connect()
    resp = await client.submit(
        "schema.config().option('graph.schema_mode').set('Development')")
    await resp.all()
    resp = await client.submit("1 + 1")
    two = await resp.one()
    assert two == 2
    print(two)
    await cluster.close()

loop.run_until_complete(test_dse(loop))
```

* It seems to run fine...:

```
$ python test_dse.py 
2
```

I haven't reviewed the changelog, but try with DSE 5.1.1 if you can, maybe something was fixed...? I can push this further using the `Goblin` mapper if you still can't get it going.

**Comment by davebshow** [comment]
Also note that `Session.submit` method just passes bytecode to the underlying `RemoteConnection`. The docstrings should be updated to reflect this. If you want to submit query strings to the Gremlin Server, please use `aiogremlin` as shown in the above example. 

Furthermore, I also tried creating a new graph using the client and it worked fine:

```python
import asyncio
from aiogremlin import driver

loop = asyncio.get_event_loop()

async def test_dse(loop):
    cluster = await driver.Cluster.open(loop)
    client = await cluster.connect()
    resp = await client.submit("system.graph('test2').create()")
    await resp.all()
    test2_client = client.alias({'g': 'test2.g'})
    resp2 = await test2_client.submit('1 + 1')
    two = await resp2.one()
    assert two == 2
    await cluster.close()
    await cluster.close()

loop.run_until_complete(test_dse(loop))
```

**Comment by oberonv1** [comment]
Just tested your above snippet independently. It also worked totally fine... 
It must be incorrect logic somewhere on my end then :(
Thanks for all the help!

Closing the issue since it wasn't a problem with goblin/aiogremlin.
