### ISSUE TITLE
Key Error for id with JanusGraph.

### ISSUE THREAD

**Issue by jbkoh** [davebshow/goblin#58]
Hi I just started learning how to use Gremlin in Python with OGM.

I used JanusGraph 0.1.1, Python 3.6.1, and Goblin 2.0 (from pip) and saw an error.

I ran the following code from the tutorial in the main page:
```python
import asyncio
from goblin import Goblin, element, properties

class Person(element.Vertex):
    name = properties.Property(properties.String)
    age = properties.Property(properties.Integer)

class Knows(element.Edge):
    notes = properties.Property(properties.String, default='N/A')

async def go(app):
    session = await app.session()
    leif = Person()
    leif.name = 'Leif'
    leif.age = 28
    jon = Person()
    jon.name = 'Jonathan'
    works_with = Knows(leif, jon)
    session.add(leif, jon, works_with)
    await session.flush()
    result = await session.g.E(works_with.id).next()
    assert result is works_with
    people = session.traversal(Person)  # element class based traversal source
    async for person in people:
        print(person)

loop = asyncio.get_event_loop()
app = loop.run_until_complete(Goblin.open(loop))
app.config_from_file("config.yaml")
app.register(Person, Knows)
loop.run_until_complete(go(app))
```

And I received an error at the last line as follows:

---
TypeError                                 Traceback (most recent call last)
<ipython-input-12-a042d423bb42> in <module>()
----> 1 loop.run_until_complete(go(app))

/home/jbkoh/anaconda3/lib/python3.6/asyncio/base_events.py in run_until_complete(self, future)
    464             raise RuntimeError('Event loop stopped before Future completed.')
    465 
--> 466         return future.result()
    467 
    468     def stop(self):

<ipython-input-11-b498be0ca216> in go(app)
      8     works_with = Knows(leif, jon)
      9     session.add(leif, jon, works_with)
--> 10     await session.flush()
     11     result = await session.g.E(works_with.id).next()
     12     assert result is works_with

/home/jbkoh/anaconda3/lib/python3.6/site-packages/goblin/session.py in flush(self)
    268         while self._pending:
    269             elem = self._pending.popleft()
--> 270             await self.save(elem)
    271 
    272     async def remove_vertex(self, vertex):

/home/jbkoh/anaconda3/lib/python3.6/site-packages/goblin/session.py in save(self, elem)
    310             result = await self.save_vertex(elem)
    311         elif elem.\_\_type\_\_ == 'edge':
--> 312             result = await self.save_edge(elem)
    313         else:
    314             raise exception.ElementError(

/home/jbkoh/anaconda3/lib/python3.6/site-packages/goblin/session.py in save_edge(self, edge)
    348             self.update_edge)
    349         hashable_id = self._get_hashable_id(result.id)
--> 350         self.current[hashable_id] = result
    351         return result
    352 

/home/jbkoh/anaconda3/lib/python3.6/weakref.py in \_\_setitem\_\_(self, key, value)
    166         if self._pending_removals:
    167             self._commit_removals()
--> 168         self.data[key] = KeyedRef(value, self._remove, key)
    169 
    170     def copy(self):
TypeError: unhashable type: 'dict'

---

How can I solve this problem? Do I misuse it?

### Update
- I checked that Jonathan and Leif are added to the database even with the error.

**Comment by rosenbrockc** [comment]
I am seeing the same thing. Traced it to the`id` of the created edge still being in the java format:

```python
{'@type': 'janusgraph:RelationIdentifier', '@value': {'value': '20b4-4ha8-glx-2wbk', '@class': 'java.util.HashMap'}}
```

This is specific to the Janus backend; it is returning a serialized dictionary for the `id` property instead of passing back the `long` `relationId` defined in the edge (https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/RelationIdentifier.java). The way around this is to generate your own function for `get_hashable_id` and pass it into the `open` method for the `goblin` app. For example:

```python
def get_hashable_id(val):
    #Use the value "as-is" by default.
    result = val
    if isinstance(val, dict) and "@type" in val and "@value" in val:
        if val["@type"] == "janusgraph:RelationIdentifier":
            result = val["@value"]["value"]
    return result
```

Then:

```python
import goblin
import asyncio
loop = asyncio.get_event_loop()
app = loop.run_until_complete(goblin.Goblin.open(loop, 
                                                 get_hashable_id=get_hashable_id))
S = loop.run_until_complete(app.session())

class A(goblin.Vertex):
    name = goblin.Property(goblin.String)
class B(goblin.Vertex):
    age = goblin.Property(goblin.Integer)
class C(goblin.Edge):
    pass

a = A()
a.name = "Conrad"
b = B()
b.age = 30
c = C(a, b)

S.add(a)
S.add(b)
S.add(c)
loop.run_until_complete(S.flush())
```

This example code works for me in the latest version.

**Comment by jbkoh** [comment]
It works for me too. Thanks for figuring it out!
