### ISSUE TITLE
Working with Set Properties

### ISSUE THREAD

**Issue by rosenbrockc** [davebshow/goblin#61]
Suppose I have a vertex `v` that has a property `hashes` of cardinality set:

```python
v.hashes = v.hashes.union(hashes)
```

Here, I want to update the property to have the union between two sets. The `v.hashes` is a `SetVertexPropertyManager` and supports all the relevant set functions. The union works great. t produces a set that has mixed object types of `int` and `VertexProperty`. However, in `abc.py`, when the assignment happens, it assumes that all the values in `val` are of primitive type. This means that `self.validate` fails because there are `VertexProperty` instances in the value, which obviously don't validate as integers because python's `int` function doesn't know what to do with them.

We could fix it by only creating a vertex property if the value isn't already one:

```python
            for v in val:
                if not isinstance(v, VertexProperty):
                    vp = vertex_prop(data_type, card=card)
                    vp.value = self.validate(v)
                else:
                    vp = v
                vertex_props.add(vp)
```

I haven't submitted a pull request because I thought you might prefer to fix this elsewhere.

**Comment by rosenbrockc** [comment]
BTW, this would be added at https://github.com/davebshow/goblin/blob/master/goblin/abc.py#L82

**Comment by davebshow** [comment]
LGTM. Wanna do a PR?
