### ISSUE TITLE
Vertex Removal `ids`

### ISSUE THREAD

**Issue by rosenbrockc** [davebshow/goblin#75]
The session objects pops the vertex hashable id from its `current` list; however, if the vertex was not first saved in the current session, then the id will not exist, so it cannot be popped. This is a trivial fix at https://github.com/davebshow/goblin/blob/master/goblin/session.py#L262:

```python
        if hashable_id in self.current:
            vertex = self.current.pop(hashable_id)
```

Which branch should I PR to?

**Comment by rosenbrockc** [comment]
Same thing for edge removal:

```python
        if hashable_id in self.current:
            edge = self.current.pop(hashable_id)
```

**Comment by davebshow** [comment]
Master will be fine.
