### ISSUE TITLE
Can't submit code via `cluster.connect` client

### ISSUE THREAD

**Issue by rosenbrockc** [davebshow/goblin#80]
When I run the following on `2.1.0rc1`

```python
import asyncio, goblin
loop = asyncio.get_event_loop()
app = loop.run_until_complete(goblin.Goblin.open(loop))
client = loop.run_until_complete(app.cluster.connect())

query = """
size = graph.getOpenTransactions().size();
for(i=0;i<size;i++) {graph.getOpenTransactions().getAt(0).rollback()};
graph.getOpenTransactions().size()
"""
result = loop.run_until_complete(client.submit(query))
print(loop.run_until_complete(result.all())) # Hangs here forever
loop.run_until_complete(client.close())
```

it hangs on the `result.all()` and I have to interrupt the kernel to get control. This used to work on the previous version. Is there an important change I am missing? I got the latest `aiogremlin` and the official `gremlin_python`.

The actual `query` doesn't matter, this is just one that I had lying around in an ipython notebook. It hangs for all my other traversal queries too.

**Comment by rosenbrockc** [comment]
I just ran the `goblin` unit tests locally and the `test_client.py` test hangs as well.

**Comment by davebshow** [comment]
You are using aiogremlin 3.2.6rc1 and gremlinpython 3.2.6 correct? What
version fo the gremlin server are you using?

**Comment by rosenbrockc** [comment]
Actually, I have gremlinpython==3.3.0; and the gremlin server is 3.2.6... Sorry, I wasn't paying attention to the version numbers. I got the correct version and it works now :P. Thanks, I like the new changes.
