### ISSUE TITLE
Its about index.

### ISSUE THREAD

**Issue by StanYaha** [davebshow/goblin#81]
Sorry, davebshow
There may be no need to create an issues.But i dont konw how to contact with you.

I want to index all vertex, is there any resolvent? I successed using index  with the property keys like
```
    vertex = await session.traversal(Suspector).has('id_number', id_number).next()
```
But when i index all the vertex, it seems the hbase scan all graph with no used elasticsearch.So it is very slow. like
```
    traversal1 = await session.traversal(Suspector).has('id_number').toList()

```

**Comment by davebshow** [comment]
Sorry I didn't answer your question. It looks like the second query is incorrect. If you have the vertex's database id (created by Janus), you can do:

```python
vert = await session.g.V(id_number).next()
```

The property keys approach in your first traversal looks good.

Hope this helps!
