### ISSUE TITLE
Problem with Edge data type

### ISSUE THREAD

**Issue by StanYaha** [davebshow/goblin#87]
```
class Relation(Edge):
    relationship = goblin.Property(goblin.String, default='unkonwn')
```
I use this to create edge.
When i create mixed index in gremlin-shell
```
graph = JanusGraphFactory.open('conf/janusgraph-hbase-es.properties')
graph.tx().rollback()
mgmt = graph.openManagement()
relationship = mgmt.getPropertyKey('relationship')
mgmt.buildIndex("RL", Edge.class).addKey(relationship).buildMixedIndex(search);
```
It reminds 
'''gremlin> mgmt.buildIndex("RL", Edge.class).addKey(relationship).buildMixedIndex("search")
Could not register new index field 'relationship' with index backend as the data type, cardinality or parameter combination is not supported.
Type ':help' or ':h' for help.
Display stack trace? [yN]n
'''
How can i correct  my relationship property key data type?Please help me!

**Comment by StanYaha** [comment]
![image](https://user-images.githubusercontent.com/25735552/31933779-ae00e6f0-b8dc-11e7-9e00-fd10fa55c6b0.png)

here is my schema
It's the data type problem.I use the goblin.String, why type is object

**Comment by davebshow** [comment]
I'm not exactly sure what is going on here. I can tell  you that Goblin doesn't do anything but make sure the property gets validated and serialized properly when it is sent over the wire, and has nothing to do with the internal data types of the Janus schema. What code did you use to create the property keys?

**Comment by StanYaha** [comment]
![image](https://user-images.githubusercontent.com/25735552/31975770-072ea4cc-b966-11e7-8c96-85a7c0a0c427.png)

![image](https://user-images.githubusercontent.com/25735552/31975710-b02d5222-b965-11e7-80ce-159c156f1f2b.png)
Here is the part of the code make property keys.Is there any problem?The data type must be string, i dont know why its object

**Comment by davebshow** [comment]
Not trying to be rude here, but you have to look in the Janus docs. This stuff doesn't have anything to do with Goblin. Those are all DataType object because you haven't created a schema, which all Janus DBs should have. Here is a link to the docs: http://docs.janusgraph.org/latest/schema.html
 
I recommend that you thoroughly read all of Janus' documentation before proceeding.

**Comment by StanYaha** [comment]
Thank you so much! I successfully created mixed index with making property key before i insert data into hbase.
Now i want to know how to use mixed index with goblin.
I read the document in gremlin-shell it uses like
```
g.V().has('propertykey', 'value').bothE().has('relationship', textCointains('key')).toList()
```
How can i use the mixed index with goblin?
