### ISSUE TITLE
Belated License change

### ISSUE THREAD

**Issue by davebshow** [davebshow/goblin#92]
Hello Goblin contributors,

I have only just realized that I should have done this several weeks ago. I would like to inform and ask the consent of all goblin contributor to change from an APGL license to Apache 2. This is a shift towards a more permissive license that will only help to stimulate community contributions and the overall improvement of this software. @leifurhauks @trojek @H-Plus-Time @rosenbrockc. Please confirm that this change is acceptable to you.

Best,

Dave

**Comment by rosenbrockc** [comment]
👍

**Comment by trojek** [comment]
:+1:

**Comment by leifurhauks** [comment]
I agree to re-license my contributions to Goblin under the Apache License v2.0.

**Comment by davebshow** [comment]
@H-Plus-Time Could you please confirm that you also agree to re-license Goblin?

**Comment by davebshow** [comment]
@H-Plus-Time I will assume your silent agreement and close this issue.
